/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform cherry_blossom_petal.glb 
Files: cherry_blossom_petal.glb [2.6KB] > C:\Users\mouli\r3f-webgpu-starter\public\cherry_blossom_petal-transformed.glb [1.58KB] (39%)
Author: Voyage (https://sketchfab.com/vrsns_voyage)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cherry-blossom-petal-a1e45d9f9796403ca855a6afa4613627
Title: Cherry blossom petal
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cherry_blossom_petal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.SakuraHanaBira} />
    </group>
  )
}

useGLTF.preload('/cherry_blossom_petal-transformed.glb')
