/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform sword1.glb 
Files: sword1.glb [201.51KB] > C:\Users\mouli\r3f-webgpu-starter\public\sword1-transformed.glb [26.67KB] (87%)
Author: Offy (https://sketchfab.com/axe163)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sword1-5ca73c3167c74bfbb123f8bb86d56e5b
Title: Sword1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sword1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={1.295} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Metal.001']} rotation={[-Math.PI / 2, 0, 0]} scale={1.357} />
    </group>
  )
}

useGLTF.preload('/sword1-transformed.glb')
